root = "."
tmp_dir = "tmp"
env_file = ".env"

[build]
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
kill_delay = 500
delay = 1000

[log]
time = true
